/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generate a file of JavaScript
 */
export interface MyComponentSchema {
  /**
   * The name of the person
   */
  name: string;
  /**
   * add name
   */
  addname?: boolean;
  /**
   * fruits
   */
  fruits?: string;
  /**
   * Generate in specific Angular CLI workspace project
   */
  project?: string;
  [k: string]: any;
}
